---
- name: Ensure httpd is installed, started, and enabled on web01
  hosts: web01
  become: yes
  tasks:
    - name: Install httpd package
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Ensure httpd service is started
      ansible.builtin.service:
        name: httpd
        state: started

    - name: Enable httpd service at boot
      ansible.builtin.service:
        name: httpd
        enabled: yes

